### PR TITLE
Bring CodeMirror up to version 5.9 + all git commits after that.

### PR DESCRIPTION
**Pull request by KamranMackey**
This PR brings CodeMirror up to version 5.9 and includes all git commits past that.

### CODE REVIEW

**Comment by MarcelGerber** [comment]
Thanks!

**Comment by KamranMackey** [comment]
No problem!

**Comment by abose** [comment]
Thanks @KamranMackey 
@MarcelGerber what changes does codemirror bring in with this update? Souldn't we update brackets submodule also with this?

**Comment by MarcelGerber** [comment]
@abose Yes, that's currently on my agenda.
I'm currently investigating an unit test failure related to the CM upgrade (https://github.com/codemirror/CodeMirror/commit/1fae53703cf4099d4f4855ef18dd14d60514c82f specifically), which seems to lie on their side, but is kind of hard to debug.

**Comment by KamranMackey** [comment]
That's weird, maybe they fixed it in a commit that was made after I made
this PR?

**Comment by MarcelGerber** [comment]
No, it hasn't been fixed yet.
Filed as https://github.com/codemirror/CodeMirror/issues/3699. Let's see how quick they are.

**Pull request merged**
